//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_COUNTRY
    {
        public REF_COUNTRY()
        {
            this.USERs = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public string COUNTRY { get; set; }
    
        public virtual ICollection<USER> USERs { get; set; }
    }
}
